language: go

go:
  - 1.13
  - 1.14
  - 1.15
  - 1.16

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=windows go build
  - GOOS=freebsd go build
  - GOARCH=386 go build

  # run tests on a standard platform
  - go test -v ./...